### ISSUE TITLE
Connect Referral Handler to Social Care Hub

### ISSUE THREAD

**Issue by awilson-AC** [chronic-care/onc-ac-project#10]
* Authenticate Referral Handler Service with Social Care Hub
* Enable authorization for Referral Handler Service to read (for later) and write into Social Care Hub

Acceptance criteria:
* Referral Handler Service successfully writes ServiceRequest, Task, and related resources into Social Care Hub (Azure Health Data Services)
* Only users with production-group-access in Azure AD should have access when connected to the production Health Data Services.

**Comment by kbertodatti** [comment]
Kiran is working on this
