### ISSUE TITLE
Connect CBO Referral App to Social Care Hub

### ISSUE THREAD

**Issue by awilson-AC** [chronic-care/onc-ac-project#11]
Authenticate CBO Referral App with Social Care Hub
Social Care Hub should authorize CBO Referral App to read/write from it.

Acceptance criteria:
* CBO Referral App is able to read referral data from Social Care Hub
* CBO Referral App is able to update Task with owner, task.status, task.businessStatus, and task.note data
* Only users with production-group-access in Azure AD should have access when connected to the production Health Data Services.

**Comment by kbertodatti** [comment]
Running into a CORs issue.
