### ISSUE TITLE
Ensure Referral Handler UI and backend Service can be deployed

### ISSUE THREAD

**Issue by awilson-AC** [chronic-care/onc-ac-project#17]

**Comment by kbertodatti** [comment]
New approach. Attempt to remove the UI layer to see if the service will deploy. @sravandigitalhie

**Comment by kbertodatti** [comment]
Update from @sravandigitalhie: Successfully got rid of the UI. When you test locally using Postman, it works. Still need to deploy on Azure and test using Postman again.
