### ISSUE TITLE
Test saving FHIR Resources into MELD and Azure Health Data Services

### ISSUE THREAD

**Issue by awilson-AC** [chronic-care/onc-ac-project#21]
Test just in Postman using transaction bundle attempt to post in both MELD and Health Data Services before writing this into code.

https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/fhir-rest-api-capabilities

Transaction bundles. Take bundle we get back from aP, modify a few elements and turn it into transaction bundle and add Task resource into it and post the whole thing as one post into Health Data Services.

**Comment by kbertodatti** [comment]
@svalluripalli I put the sample bundle on github. Here's the path: oncleap/ac-samples/ServiceRequest _Include 09142023.json

https://github.com/chronic-care/mcc-sample-data/blob/main/oncleap/ac-samples/ServiceRequest%20_Include%2009142023.json

**Comment by kbertodatti** [comment]
From @sravandigitalhie - Successfully put the ServiceRequest bundle in the patch and pushed it into MELD and Azure Health Data Services.
