### ISSUE TITLE
As a CBO Referral App user, I want to change the status on a referral so everyone knows what the next step is

### ISSUE THREAD

**Issue by awilson-AC** [chronic-care/onc-ac-project#24]
Using FHIR Task Resource to capture owners, Task Business status, Task Status, and Task Notes.
1 Service Request (Referral) has 1 Task associated with it.

Acceptance criteria:
- A CBO user can select a status from the "Assign Status" dropdown menu.
- When the CBO user clicks "Save", the status in the "Assign Status" field is saved in the Task Resource in the Social Care Hub.
- If the CBO user exits out of the referral dialog box and opens it up again, they should see the new status in the same session (or if they open the app again).

**Comment by kbertodatti** [comment]
- Timelines for the API connections to test and validate the triggering (provide a service that's running that can receive the FHIR List resource; this should be early November) and 
- import into your platform (RHS needs to send several more queries to aP and then Social Care Hub; should be doable by mid-December). 
  - Also need service to service access to post to Social Care Hub.
- (Separate out "create a Task for the ServiceRequest" and post that to Social Care Hub.)
- Timelines for testing the API call's back to aP to pull necessary data to support the workflows as the team prepares for the trainings coming up soon
 
Need to ask jeremy for the query parameters for the _include ( @kbertodatti to look for that)

**Comment by kbertodatti** [comment]
Tested using Staging/Testing version.
Was able to change a status in dialog window. The dialog window closes when I click "Save".
Need to click REFRESH.
After refreshing the dashboard, the new status is shown when I open the referral dialog window.

Enhancement: @sravandigitalhie to explore if it's a quick fix to not need to refresh the page to see the changes. Or maybe if there's a way to automatically refresh the page without the user needing to click refresh.
