### ISSUE TITLE
Update CBO app to read FHIR extension for gender identity and sexual orientation

### ISSUE THREAD

**Issue by savanahmueller** [chronic-care/onc-ac-project#36]
In the referral dialog box, the patient demographics section - update the code to read FHIR patient extension for **gender identity** and **sexual orientation** instead of hardcoded data.

**Comment by kbertodatti** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWQyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a9b68b69cfc9f42a2e6d8c48d1b04af503a2158/image.png)

**Comment by kbertodatti** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekoyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0676c8479d82ac589eae3cf505f65dde2c72507/image.png)
