### ISSUE TITLE
As a CH user, I want to read the initial referral note in a reader-friendly format so I can quickly understand the context for the referral

### ISSUE THREAD

**Issue by savanahmueller** [chronic-care/onc-ac-project#38]
In the referral dialog box, display the initial note text (ServiceRequest.Note) in a reader-friendly format (i.e. no %nbsp in text).

**Comment by kbertodatti** [comment]
This is completed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekIyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c79aebe828f7758b5ddb875e01426133eaf6fb17/image.png)
