### ISSUE TITLE
Adding note to referral

### ISSUE THREAD

**Issue by savanahmueller** [chronic-care/onc-ac-project#43]
As a CH user, I want to add a note to a referral so that I can document relevant info about the referral management.

Chicago House users should have a way to leave notes like alternate contact info, patient demographics info, details about attempts to contact the client, client preferences, etc.

Acceptance criteria:
- In the referral dialog box, user can type a note in the "Add Notes (optional)" field.
- When they click "Save", the note should be saved to the Social Care Hub. Provenance includes date created and Author should be whoever is logged into the app.
- Note authored should be displayed in the "Notes History" tab. (May need to break this one into its own story).

Notes for future versions of the app:
- May want a way to leave notes associated with the Patient Resource and not Task Resource (i.e., Patient's pronouns are he/him should be associated with the Patient, not just the particular Referral Task).

**Comment by kbertodatti** [comment]
<img width="926" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzNOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--637e2455b8282ba426192add2e2310a3ed61fb33/image.png" alt="image.png" />

Nothing happens when I click "Save" after typing a note in for that referral.

**Comment by kbertodatti** [comment]
More clarity on the bug: You can only save the note when you change the owner.
