### ISSUE TITLE
Determine what trigger and what information about a referral needs to be returned to HAH

### ISSUE THREAD

**Issue by savanahmueller** [chronic-care/onc-ac-project#45]
NEED TO SCOPE THIS OUT. Basically, what do we need to include in documentReference that goes back to HAH?
- What triggers a referral to enter an end status?
- What information about the referral needs to be relayed back to HAH?

Update text which appears in an inbox in aP that there is a new document that might refer back to the service request
**Comes back as a consultation note**
No way currently to update the order

Design doc: https://docs.google.com/document/d/1k6Tz6J_4zNX_cupBBRmvDPUwOtUZuXmy-CwRgFYVsoE/edit

**Comment by kbertodatti** [comment]
Decision from 1/31/24 meeting with AC was to give a specific person from HAH access to the CBO Referral App so they can see the outcomes of the referrals.
