### ISSUE TITLE
Define Task.businessStatus to be used by CH users referral management

### ISSUE THREAD

**Issue by savanahmueller** [chronic-care/onc-ac-project#47]
Define [Task.businessStatus](https://hl7.org/fhir/R4/task-definitions.html#Task.businessStatus) for CH referral management process. May need 2 sets of businessStatus for HOPE and TLC.

Correlate Task.businessStatus with [Task.status](https://hl7.org/fhir/R4/valueset-task-status.html)
- draft
- requested
- received
- accepted
- rejected
- ready
- cancelled
- in-progress
- on-hold
- failed
- completed
- entered-in-error

**Comment by kbertodatti** [comment]
Added table for proposed business statuses: https://docs.google.com/document/d/1SFMyUosknQ6bE8dT3KDjRoxvU7N3D4JBiIbvxI5vmCg/edit?usp=sharing

Proposed CH referral management task and business status flow: https://www.figma.com/file/cQWKFor8t4IJnu7Qz1wHNQ/CBO-Referral-Management-Task-and-Business-Status?type=whiteboard&node-id=0-1&t=xwvXZS3R3IkHbhF7-0

**Comment by kbertodatti** [comment]
Agreed with Shelly/Jeremy to proceed with this list:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEY0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7fc0d0a81200ef5795eb1dadf94e6c88e1c902e1/image.png)
