### ISSUE TITLE
Default settings to show newly received referrals first

### ISSUE THREAD

**Issue by savanahmueller** [chronic-care/onc-ac-project#49]
- Upon login, is there the ability to set default setting to sort all referrals in a section by status? Is there the ability to have different default settings for each section (New, Active, Archive)?

Done:
* If new referrals show at the top of the list on the referral dashboard.

**Comment by kbertodatti** [comment]
Just QA'ed. Looks like `Received` referrals are defaulting to show first.

<img width="1156" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejlDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7806a3068fde5774106b4f47c41a71722c251cc3/image.png" alt="image.png" />
