### ISSUE TITLE
Enhance Referral Handler Service to make query back to aP

### ISSUE THREAD

**Issue by drdavec** [chronic-care/onc-ac-project#5]
Perform FHIR queries to Alliance Chicago FHIR endpoint to obtain complete FHIR resources from the List (DETAILS TBD)
Full doc: https://docs.google.com/document/d/1KZX-tNpmN1rIss56pqUFkgwjwOdLCHSPUQaRiD3KMQk/edit?usp=sharing

From Jeremy:
Here is the current query for finding the service request that would be used from the API.

Once list of patients is provided, the API would perform the following query against each patientID to obtain the full Service request with all extensions included.  As we discussed on the call, the _Include statement automatically pulls in the related resources in the ServiceRequest

/hhAPIServer/fhir/r4/ServiceRequest?_count=10000&_format=json&_summary=data&patient={{patientid}}&category=referrals&code=ZZZZZ,ZZZZZ-2&_include=ServiceRequest:*&_lastUpdated=ge2023-08-11T09:01:11

+++
Remove "last updated" parameter for right now and add this in later when we figure out how to save the last time we queried.

**Comment by NoahWGeorge** [comment]
test
