### ISSUE TITLE
Prepare sample trigger and info on FHIR List for referral

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/onc-ac-project#56]

**Comment by drdavec** [comment]
Text of email sent to Jeremy:

See the attached sample of a FHIR List resource that we would like to be used for subscription notifications that you produce from Athena.  This is a very simple example template and fully valid per the FHIR spec:

http://hl7.org/fhir/R4/list.html

JSON file attached and copied inline below.  I included a reference to the Patient (or multiple Patient resources) that are connected with the list of ServiceRequest resources.  Including the Patient ref is optional, but will be helpful in our referral handler to use for sending other queries, e.g. for Condition or MedicationRequest.  If not included, we can extract the Patient from each ServiceRequest.

Let me know if you have any questions.

{
    "resourceType": "List",
    "id": "821ea3c1-011f-4f70-a8ae-299043b7e0be",
    "status": "current",
    "mode": "changes",
    "date": "2023-10-09T22:17:00+11:00",
    "entry": [
        {
            "item": {
                "reference": "Patient/2001157662078660"
            }
        },
        {
            "item": {
                "reference": "ServiceRequest/2009624124426130"
            }
        },
        {
            "item": {
                "reference": "ServiceRequest/2008836135127130"
            }
        }
    ]
}
