### ISSUE TITLE
Add ability to read and display the Task Resource

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/onc-ac-project#63]
The CBO Referral App should be able to read Tasks associated with Service Requests.
The CBO Referral App view should be updated with Task Resource information:

1. On the dashboard page, Update "Date Received" value to Task Resource authoredOn (display MM/DD/YYYY)
2. On the referral dialog box:
- Assigned Status should display the businessStatus
- Assigned Owner should display Owner (Display Practitioner after identifying PractitionerRole as "Care Manager")
- Notes History should display Task.note (Annotation includes author, time (display date), text)

Reference: https://docs.google.com/document/d/1SFMyUosknQ6bE8dT3KDjRoxvU7N3D4JBiIbvxI5vmCg/edit?usp=sharing

**Comment by kbertodatti** [comment]
@drdavec - it seems like @sravandigitalhie is not seeing "Task Note" in the array. Can you help troubleshoot?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHFZQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b68703ab081e9bc3cf069ca5d4563da00c5c1eb5/image.png)

**Comment by drdavec** [comment]
@sravandigitalhie and @kbertodatti The Notes array you show here are INSTANCES of a FHIR Task resource.  Our sample data for Task does not include a Task.note value, so they do not show in in that instance data.  I created these Task samples based on what we expect to be created by the referral handler with the initial state that would not include any notes.  Task.note should be added by a user of the app.

Would you like these Task samples to reflect tasks that are already assigned, and include one or two notes in the sample?  For testing the UI display of a Task already underway?  Or maybe update one of the Tasks to have an assigned in progress status with notes?  And leave the others as initial, unassigned tasks?

**Comment by sravandigitalhie** [comment]
@drdavec and @kbertodatti  yeah, if there are more than one tasks with notes, it would be helpful in testing the UI.

**Comment by kbertodatti** [comment]
@drdavec thanks for the explanation. I think it would be helpful to have one task assigned to one owner with the status "in progress" and a note that says "Attempted to contact client via phone number on 10/31 and left a voicemail."

**Comment by kbertodatti** [comment]
From @drdavec :
We have 4 Task resources in our sample data. I updated two to include notes. The note Annotation often contains only “text” (as in the resources from AthenaPractice), but I included the optional “authorReference” and “time” elements, if you want to display those. I added 2 notes to one of the Tasks for testing to assure that the app displays multiple notes per task. All of the changes described here are now added to the Social Care Hub MELD sandbox for testing.

Those two Tasks also now have an “owner” assigned, I changed the status to “in-progress” and the businessStatus to “Assigned” (not sure if this is the right business status, and we still need to define a CodeSystem with codes for these).

In order to assign the Task.owner, and to set the note.authorReference, I had to add Practitioners for the CH case managers. I created 4 new Practitioner resources for:

- Kevin Pleasant
- Armando Garcia
- Owen Davis
- Khalina Goodlow

There is nothing in a Practitioner resource to indicate the role of this person; we also have Practitioner resources for the AC clinicians who created those referrals. So, we need PractitionerRole resources to assign the Case Manager role to these four Practitioners.

Using the US Core value set for PractitionerRole codes, I used the code for “Case Manager”
http://hl7.org/fhir/us/core/STU3.1.1/ValueSet-us-core-provider-role.html

Another important use for these PractitionerRole resources is to query the Social Care Hub for all available Case Managers that might be assigned to a Task. You can now search search the Social Care Hub for all Case Managers using this query:
  PractitionerRole?role=171M00000X

And use the result to populate the app pull-down list of case managers that can be assigned. Use should use a PractitionerRole in the Task.owner reference, as in the two Task resources that I updated.

You can see these four Practitioner and PractitionerRole resources in GitHub here:
https://github.com/chronic-care/mcc-sample-data/blob/main/oncleap/hub/01-CaseWorkers.json

And the four Task resources here:
https://github.com/chronic-care/mcc-sample-data/blob/main/oncleap/hub/06-Task.json

**Comment by kbertodatti** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzNBQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eed25aa66a2c373b8a9c8de34c95e38182ac75f4/image.png)

@sravandigitalhie can we update the UI so that the dropdown list of statuses are all on one line? (or can we put lines between the statuses to show them more clearly? i.e., the one that's running onto the second line is "Service not Needed"

**Comment by sravandigitalhie** [comment]
@kbertodatti Sure, will modify it.
