### ISSUE TITLE
New Patient creation screen UI

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/onc-ac-project#78]
<img width="793" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMExjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--770b0818888aac7538dcf11b4a5b7a396d64dd30/image.png" alt="image.png" />

**Comment by kbertodatti** [comment]
Replace Sexual Orientation with "Gender Identity" dropdown.

FHIR extension > Patient.extension:genderIdentity

Dropdown:
Identifies as nonbinary gender
Male-to-female transsexual
Female-to-male transsexual
Identifies as non-conforming gender
Identifies as female gender
Identifies as male gender
Other
Unknown
Asked but declined

https://vsac.nlm.nih.gov/valueset/2.16.840.1.113762.1.4.1021.32/expansion

**Comment by sravandigitalhie** [comment]
Modified the UI accordingly, below is the screenshot
<img width="494" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzNxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4dfb48ce7fd84fced8fb27280b4a4ef215f5bc5/image.png" alt="image.png" />

**Comment by kbertodatti** [comment]
- Add sexual orientation https://build.fhir.org/ig/HL7/cdmh/CodeSystem-pcornet-sexual-orientation.html
- Alphabetize dropdown items
- Change "Gender" to "Administrative Gender"
- Move "Sex at Birth" "Administrative Gender" and "Gender Identity" closer together
- Add tooltip to "Administrative Gender" (and other two). Tooltip for Admin Gender = "Also called legal gender or gender marker."

**Comment by sravandigitalhie** [comment]
Modified Accordingly, below is the screenshot: 
<img width="499" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3Y4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f92b641f72a7acfa64491b06544997c72a80d5e/image.png" alt="image.png" />
